name: Federated SDK issue template
description: |
  Federated issue management across all OpenFeature SDKs.
  Please note that sub-issues will only be created for authorized users.
labels:
  - federated
  - sdk

body:
  - type: markdown
    attributes:
      value: |
        ## Federated SDK issue template
        This issue is for creating sub-issues across all OpenFeature SDKs.
        Please note that sub-issues will only be created for authorized users.
        If you are not authorized, please create a new issue in the relevant SDK repository.
  - type: textarea
    attributes:
      label: Parent issue description
      description: The description of the parent issue.
      value: |
        Please add information about the issue you want to create.
        You can use Markdown syntax to format your text.
  - type: markdown
    attributes:
      value: |
        ## Sub-Issue Creation
        Please provide the details for the sub-issue you want to create.
        The sub-issue will be created in the relevant SDK repository.
  - type: input
    id: sub-issue-title
    attributes:
      label: Sub-Issue Title
      description: The title of the sub-issue.
  - type: textarea
    id: sub-issue-body
    attributes:
      label: Implementation Details
      description: |
        Please provide a detailed description of the implementation details for the sub-issue.
        You can use Markdown syntax to format your text.